version: '3'
services:
  nim:
    build: ./docker/nim
    tty: true
    ports:
      - 9010:5000
    volumes:
      - .:/application
    depends_on:
      - db

  rust:
    build: ./docker/rust
    tty: true
    ports:
      - 9011:5000
    volumes:
      - .:/application
    depends_on:
      - db

  dotnet:
    build: ./docker/dotnet
    tty: true
    ports:
      - 9012:5000
    volumes:
      - .:/application
    depends_on:
      - db

  db:
    image: postgres:alpine #pgsqlが準備されているimageを指定
    tty: true
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
